#Gradle
org.gradle.jvmargs=-Xmx12G -Dfile.encoding=UTF-8 -Dkotlin.daemon.jvm.options\="-Xmx2048M"
org.gradle.caching=true
#org.gradle.configuration-cache=true
org.gradle.configuration-cache.problems=warn

#Kotlin
kotlin.code.style=official
#MPP
kotlin.mpp.enableCInteropCommonization=true
#Android
android.useAndroidX=true
android.nonTransitiveRClass=true

kotest.framework.dump.config=true
testBalloon.reportingMode=files
ksp.incremental.log=true